name: Android CI

#Events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Define environment variables for your secrets
      SECRET_GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Create secrets.properties
        run: |
          echo "SECRET_GITHUB_TOKEN=${{ secrets.SECRET_GITHUB_TOKEN }}" >> ./secrets.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clean build directory
        run: ./gradlew clean

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
